"""Tourbillon test case driver (example/tourbillon).

Demonstrates the approved Mechanism DSL set needed to build a tourbillon
(rotating carriage) object: fixed fourth wheel (`gear`), rotating `cage`
carrying an `escape_wheel` and `balance_wheel`, a `lever` (pallet fork),
a `hairspring`, and `jewel` bearings.

Each part is generated by the deterministic (cadquery) CAD runtime and the
standard HTML assembly viewer is emitted. A tourbillon-specific containment
check (`check_tourbillon_constraints`) verifies the cage physically encloses
its carried escapement wheels; a violation surfaces the reserved
`ASSEMBLY_CONSTRAINT_FAILED` contract error code.
"""
from __future__ import annotations

import json
from pathlib import Path

from cad_agent.assembly_checks import AssemblyPart, BBox, check_tourbillon_constraints
from cad_agent.platform_poc import run_assembly_pipeline
from cad_agent.schema_gate import validate_against_schema

ROOT = Path(__file__).resolve().parents[2]
EXAMPLE_DIR = Path(__file__).resolve().parent
ARTIFACT_DIR = ROOT / "artifacts" / "tourbillon"
ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)

# part_id, traceability_id, dsl filename, (cx, cy) center mm, nominal r mm, zmin mm, zmax mm
# z slabs are stacked so each part touches (does not overlap) its neighbour, avoiding
# false AABB interference for nested tourbillon parts under the surrogate.
PARTS = [
    ("fixed_wheel", "tr_dsl_tb_fixed_wheel", "dsl_fixed_wheel.json", 0.0, 0.0, 7.0, 0.0, 1.0),
    ("cage", "tr_dsl_tb_cage", "dsl_cage.json", 0.0, 0.0, 12.0, 3.0, 4.0),
    ("escape_wheel", "tr_dsl_tb_escape", "dsl_escape_wheel.json", 3.0, 0.0, 6.0, 6.75, 7.0),
    ("balance_wheel", "tr_dsl_tb_balance", "dsl_balance_wheel.json", -2.0, 0.0, 7.0, 8.25, 9.0),
    ("lever", "tr_dsl_tb_lever", "dsl_lever.json", 3.0, 0.0, 6.0, 9.25, 10.0),
    ("hairspring", "tr_dsl_tb_hairspring", "dsl_hairspring.json", 0.0, 0.0, 4.2, 10.25, 11.0),
    ("jewel", "tr_dsl_tb_jewel", "dsl_jewel.json", 0.0, 0.0, 1.5, 10.5, 12.0),
]


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    requirement = load(EXAMPLE_DIR / "requirement.json")
    specification = load(EXAMPLE_DIR / "specification.json")
    schema_checks = {
        "requirement": [c.status for c in validate_against_schema(requirement, "requirement")],
        "specification": [c.status for c in validate_against_schema(specification, "specification")],
    }

    parts = []
    for part_id, tr_id, dsl_file, cx, cy, r, zmin, zmax in PARTS:
        dsl = load(EXAMPLE_DIR / dsl_file)
        parts.append(
            {
                "part_id": part_id,
                "traceability_id": tr_id,
                "dsl": dsl,
                "cx": cx,
                "cy": cy,
                "r": r,
                "zmin": zmin,
                "zmax": zmax,
            }
        )

    pipeline = run_assembly_pipeline(
        parts,
        specification=specification,
        requirement=requirement,
        output_dir=ARTIFACT_DIR,
    )

    # Reconstruct AssemblyParts (mirroring the pipeline placement) for the tourbillon check.
    placement = {p["part_id"]: (p["cx"], p["cy"], p["zmin"]) for p in parts}
    asm_parts: list[AssemblyPart] = []
    for g in pipeline["gears"]:
        cx, cy, zmin = placement[g["part_id"]]
        bb = g["bbox_mm"] or {}
        hx = float(bb.get("length", 0.0)) / 2.0
        hy = float(bb.get("width", 0.0)) / 2.0
        hz = float(bb.get("height", 0.0)) / 2.0
        asm_parts.append(
            AssemblyPart(
                part_id=g["part_id"],
                traceability_id=g["traceability_id"],
                bbox=BBox(cx - hx, cy - hy, zmin, cx + hx, cy + hy, zmin + hz),
            )
        )
    tourbillon = check_tourbillon_constraints(asm_parts)
    tourbillon_pass = tourbillon.status == "pass"

    runtime_pass = all(g["dsl_ast_status"] == "pass" and g["runtime_status"] == "pass" for g in pipeline["gears"])
    assembly_pass = pipeline["assembly"]["status"] == "pass"

    overall = (
        all(s == "pass" for s in schema_checks["requirement"])
        and all(s == "pass" for s in schema_checks["specification"])
        and runtime_pass
        and assembly_pass
        and tourbillon_pass
    )

    results = {
        "example": "tourbillon",
        "schema_checks": schema_checks,
        "assembly_status": pipeline["assembly"]["status"],
        "tourbillon_constraint": tourbillon.as_dict(),
        "tourbillon_pass": tourbillon_pass,
        "parts": pipeline["gears"],
        "overall_status": "pass" if overall else "fail",
    }

    out_path = EXAMPLE_DIR / "tourbillon_validation_report.json"
    out_path.write_text(json.dumps(results, ensure_ascii=False, indent=2), encoding="utf-8")

    print(json.dumps(results, ensure_ascii=False, indent=2))
    return 0 if overall else 1


if __name__ == "__main__":
    raise SystemExit(main())
